//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class lawyerDBEntities : DbContext
    {
        public lawyerDBEntities()
            : base("name=lawyerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GET_CASOS_Result> GET_CASOS(Nullable<decimal> userID, Nullable<decimal> token)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(decimal));
    
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_CASOS_Result>("GET_CASOS", userIDParameter, tokenParameter);
        }
    
        public virtual ObjectResult<GET_GASTOS_Result> GET_GASTOS(Nullable<decimal> userID, Nullable<decimal> token, Nullable<decimal> casoID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(decimal));
    
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(decimal));
    
            var casoIDParameter = casoID.HasValue ?
                new ObjectParameter("CasoID", casoID) :
                new ObjectParameter("CasoID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_GASTOS_Result>("GET_GASTOS", userIDParameter, tokenParameter, casoIDParameter);
        }
    
        public virtual ObjectResult<GET_HIJO_Result> GET_HIJO(Nullable<decimal> userID, Nullable<decimal> token, Nullable<decimal> casoID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(decimal));
    
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(decimal));
    
            var casoIDParameter = casoID.HasValue ?
                new ObjectParameter("CasoID", casoID) :
                new ObjectParameter("CasoID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_HIJO_Result>("GET_HIJO", userIDParameter, tokenParameter, casoIDParameter);
        }
    
        public virtual ObjectResult<GET_INGRESO_Result> GET_INGRESO(Nullable<decimal> userID, Nullable<decimal> token, Nullable<decimal> casoID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(decimal));
    
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(decimal));
    
            var casoIDParameter = casoID.HasValue ?
                new ObjectParameter("CasoID", casoID) :
                new ObjectParameter("CasoID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_INGRESO_Result>("GET_INGRESO", userIDParameter, tokenParameter, casoIDParameter);
        }
    
        public virtual ObjectResult<GET_INICIO_Result> GET_INICIO(Nullable<decimal> userID, Nullable<decimal> token, Nullable<decimal> casoID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(decimal));
    
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(decimal));
    
            var casoIDParameter = casoID.HasValue ?
                new ObjectParameter("CasoID", casoID) :
                new ObjectParameter("CasoID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_INICIO_Result>("GET_INICIO", userIDParameter, tokenParameter, casoIDParameter);
        }
    
        public virtual ObjectResult<GET_RELACIONES_Result> GET_RELACIONES(Nullable<decimal> userID, Nullable<decimal> token, Nullable<decimal> casoID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(decimal));
    
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(decimal));
    
            var casoIDParameter = casoID.HasValue ?
                new ObjectParameter("CasoID", casoID) :
                new ObjectParameter("CasoID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_RELACIONES_Result>("GET_RELACIONES", userIDParameter, tokenParameter, casoIDParameter);
        }
    
        public virtual ObjectResult<LOGIN_Result> LOGIN(string eMAIL, string password, string device)
        {
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var deviceParameter = device != null ?
                new ObjectParameter("device", device) :
                new ObjectParameter("device", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOGIN_Result>("LOGIN", eMAILParameter, passwordParameter, deviceParameter);
        }
    
        public virtual ObjectResult<string> SET_INICIO(Nullable<decimal> userID, Nullable<decimal> token, Nullable<decimal> casoID, string type, string value)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(decimal));
    
            var tokenParameter = token.HasValue ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(decimal));
    
            var casoIDParameter = casoID.HasValue ?
                new ObjectParameter("CasoID", casoID) :
                new ObjectParameter("CasoID", typeof(decimal));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SET_INICIO", userIDParameter, tokenParameter, casoIDParameter, typeParameter, valueParameter);
        }
    
        public virtual ObjectResult<SIGN_UP_Result> SIGN_UP(string eMAIL, string password, string registro, string name)
        {
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var registroParameter = registro != null ?
                new ObjectParameter("registro", registro) :
                new ObjectParameter("registro", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SIGN_UP_Result>("SIGN_UP", eMAILParameter, passwordParameter, registroParameter, nameParameter);
        }
    }
}
